DarulAman/Controllers/AdminSideFormController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DarulAman.Models;

namespace DarulAman.Controllers
{
    public class AdminSideFormController : Controller
    {
        Model1 db = new Model1();
   
        public ActionResult GeneralRegistration()
        {
            var g = db.tbl_GeneralRegistrationForm.ToList();
            return View(g);
        }  
       
        public ActionResult ContactRegistration()
        {
            var c = db.tbl_Contact.ToList();
            return View(c);
        }
        public ActionResult MyProfile()
        {
            var tbl_Admin = db.tbl_Admin.Include(t => t.tbl_AccessLevel);
            return View(tbl_Admin.ToList());
        }
        // GET: tbl_Admin/Edit/5
        public ActionResult MyProfileEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Admin tbl_Admin = db.tbl_Admin.Find(id);
            if (tbl_Admin == null)
            {
                return HttpNotFound();
            }
            ViewBag.ACCESS_LEVEL_FID = new SelectList(db.tbl_AccessLevel, "ACCESS_LEVEL_ID", "NAME", tbl_Admin.ACCESS_LEVEL_FID);
            return View(tbl_Admin);
        }

        // POST: tbl_Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MyProfileEdit([Bind(Include = "ADMIN_ID,FIRST_NAME,LAST_NAME,EMAIL,CONTACT,PASSWORD,ADDRESS,STATUS,ACCESS_LEVEL_FID")] tbl_Admin tbl_Admin)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Admin).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyProfile");
            }
            ViewBag.ACCESS_LEVEL_FID = new SelectList(db.tbl_AccessLevel, "ACCESS_LEVEL_ID", "NAME", tbl_Admin.ACCESS_LEVEL_FID);
            return View(tbl_Admin);
        }



    }
}

DarulAman/Views/AdminSideForm/ContactRegistration.cshtml
@model IEnumerable<DarulAman.Models.tbl_Contact>
@{ 
    int no = 0;
}
<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Contact</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!---------------------Table------------------------------>
<div class="midde_cont">
    <div class="container-fluid">
        <div  class="row">
<div class="col-md-12">
    <div class="white_shd full margin_bottom_30">
        <div class="full graph_head">
            <div class="heading1 margin_0">
                <h2>Contact Form</h2>
            </div>
        </div>
        <div class="table_section padding_infor_info">
            <div class="table-responsive-sm">
                <table class="table table-active table-bordered">
                    <thead>
                        <tr>
                            <th>Sr#</th>
                            <th>ID</th>
                            <th>FIRST NAME</th>
                            <th>LAST NAME</th>
                            <th>EMAIL</th>
                            <th>User ID</th>
                            <th>CONTACT</th>
                            <th>MESSAGE</th>
                            <th>DATE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var c in Model)
                        {
                            no++;
                        <tr>
                            <td>@no</td>
                            <td>@c.CONTACT_ID</td>
                            <td>@c.FIRST_NAME</td>
                            <td>@c.LAST_NAME</td>
                            <td>@c.EMAIL</td>
                            <td>@c.ID</td>
                            <td>@c.CONTACT</td>
                            <td>@c.MESSAGE</td>
                            <td>@DateTime.Parse(c.DATE.ToString()).ToLongDateString()</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

DarulAman/Views/AdminSideForm/GeneralRegistration.cshtml
@model IEnumerable<DarulAman.Models.tbl_GeneralRegistrationForm>
@{ 
    int no = 0;
}
<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>General Registration</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!---------------------Table------------------------------>
<div class="midde_cont">
    <div class="container-fluid">
        <div  class="row">
<div class="col-md-12">
    <div class="white_shd full margin_bottom_30">
        <div class="full graph_head">
            <div class="heading1 margin_0">
                <h2>Regestration</h2>
            </div>
        </div>
        <div class="table_section padding_infor_info">
            <div class="table-responsive-sm">
                <table class="table table-active table-bordered">
                    <thead>
                        <tr>
                            <th>Sr#</th>
                            <th>ID</th>
                            <th>FIRST NAME</th>
                            <th>LAST NAME</th>
                            <th>CONTACT</th>
                            <th>EMAIL</th>
                            <th>PROFESSION</th>
                            <th>GENDER</th>
                            <th>COUNTRY</th>
                            <th>CITY</th>
                            <th>ADDRESS</th>
                            <th>MESSAGE</th>
                            <th>DATE</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var g in Model)
                        {
                            no++;
                        <tr>
                            <td>@no</td>
                            <td>@g.GENERAL_ID</td>
                            <td>@g.FIRST_NAME</td>
                            <td>@g.LAST_NAME</td>
                            <td>@g.CONTACT</td>
                            <td>@g.EMAIL</td>
                            <td>@g.PROFESSION</td>
                            <td>@g.GENDER</td>
                            <td>@g.COUNTRY</td>
                            <td>@g.CITY</td>
                            <td>@g.ADDRESS</td>
                            <td>@g.MESSAGE</td>
                            <td>@DateTime.Parse(g.DATE.ToString()).ToLongDateString()</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>

DarulAman/Views/AdminSideForm/MyProfile.cshtml
@model IEnumerable<DarulAman.Models.tbl_Admin>
@using DarulAman.Models
 

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Index</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<br />

<table class="table">
    <tr>
       
        <th>
            FIRST_NAME
        </th>
        <th>
            LAST_NAME
        </th>
        <th>
            EMAIL
        </th>
        <th>
            CONTACT
        </th>
        <th>
            PASSWORD
        </th>
        <th>
            ADDRESS
        </th>
        
        <th>
            STATUS
        </th>
        
        <th>
            ACCESS-LEVEL
        </th>
        
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        tbl_Admin a = (tbl_Admin)Session["Admin"];
        if (a.ADMIN_ID == item.ADMIN_ID)
        {
        <tr>

           
            <td>
                @item.FIRST_NAME
            </td>
            <td>
                @item.LAST_NAME
            </td>
            <td>
                @item.EMAIL
            </td>
            <td>
                @item.CONTACT
            </td>
            <td>
                @item.PASSWORD
            </td>
            <td>
                @item.ADDRESS
            </td>
          <td >
                @item.STATUS
            </td>
            <td>
                @item.ACCESS_LEVEL_FID
            </td>
          
            <td>
                <a href="@Url.Action("MyProfileEdit", "AdminSideForm", new { id = item.ADMIN_ID })">
                    <i class="fa fa-edit btn btn-success  "></i>
                </a>
               
            </td>

        </tr>
        }
    }

</table>

DarulAman/Views/AdminSideForm/MyProfileEdit.cshtml
@model DarulAman.Models.tbl_Admin

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Edit</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <p class="heading-center" align="center">Admin</p>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ADMIN_ID)

    <div class="form-group">
        @Html.LabelFor(model => model.FIRST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FIRST_NAME, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FIRST_NAME, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LAST_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LAST_NAME, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LAST_NAME, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CONTACT, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CONTACT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CONTACT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PASSWORD, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ADDRESS, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ADDRESS, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (Model.ACCESS_LEVEL_FID != 1)
    {
        <div class="form-group">
            <label hidden class="read-only">STATUS *</label><div class="col-md-10">
              <label hidden class="read-only">
                  @Html.EditorFor(model => model.STATUS, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                  </label>
            @Html.ValidationMessageFor(model => model.STATUS, "", new { @class = "text-danger" })
</div>
        </div>

        <div class="form-group">
            <label hidden class="read-only">ACCESS_LEVEL_FID</label>
            <div class="col-md-10">
                <label hidden class="read-only">@Html.DropDownList("ACCESS_LEVEL_FID", null, htmlAttributes: new { @class = "form-control", @readonly = "" })</label>
                @Html.ValidationMessageFor(model => model.ACCESS_LEVEL_FID, "", new { @class = "text-danger" })
            </div>
        </div>
    }

else { 
        <div class="form-group">
            @Html.LabelFor(model => model.STATUS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.STATUS, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.ADDRESS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>ACCESS_LEVEL_FID</label>
            <div class="col-md-10">
                <label class="read-only">@Html.DropDownList("ACCESS_LEVEL_FID", null, htmlAttributes: new { @class = "form-control"})</label>
                @Html.ValidationMessageFor(model => model.ACCESS_LEVEL_FID, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-outline-info btn-custom btn-lg" />
        </div>
    </div>
</div>
}


    <a href="@Url.Action("MyProfile","AdminSideForm")"><input type="submit" class="btn btn-custom btn-outline-warning btn-lg" value="Back to Profile"/></a>