DarulAman/Models/tbl_Book.cs
namespace DarulAman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tbl_Book
    {
        [Key]
        public int BOOK_ID { get; set; }

        [Required]
        [StringLength(50)]
        public string BOOK_NAME { get; set; }

        [Required]
        [StringLength(50)]
        public string BOOK_AUTHOR { get; set; }

        public string BOOK_PICTURE { get; set; }

        public string BOOK_DETAIL { get; set; }

        [Required]
        public string BOOK_PDF { get; set; }

        public int CATEGORY_FID { get; set; }

        public virtual tbl_BookCategory tbl_BookCategory { get; set; }
    }
}

DarulAman/Controllers/tbl_BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DarulAman.Models;

namespace DarulAman.Controllers
{
    public class tbl_BookController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_Book
        public ActionResult Index()
        {
            var tbl_Book = db.tbl_Book.Include(t => t.tbl_BookCategory);
            return View(tbl_Book.ToList());
        }

        // GET: tbl_Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Book tbl_Book = db.tbl_Book.Find(id);
            if (tbl_Book == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Book);
        }

        // GET: tbl_Book/Create
        public ActionResult Create()
        {
            ViewBag.CATEGORY_FID = new SelectList(db.tbl_BookCategory, "CATEGORY_ID", "CATEGORY_NAME");
            return View();
        }

        // POST: tbl_Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BOOK_ID,BOOK_NAME,BOOK_AUTHOR,BOOK_PICTURE,BOOK_DETAIL,BOOK_PDF,CATEGORY_FID")] tbl_Book tbl_Book)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Book.Add(tbl_Book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CATEGORY_FID = new SelectList(db.tbl_BookCategory, "CATEGORY_ID", "CATEGORY_NAME", tbl_Book.CATEGORY_FID);
            return View(tbl_Book);
        }

        // GET: tbl_Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Book tbl_Book = db.tbl_Book.Find(id);
            if (tbl_Book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CATEGORY_FID = new SelectList(db.tbl_BookCategory, "CATEGORY_ID", "CATEGORY_NAME", tbl_Book.CATEGORY_FID);
            return View(tbl_Book);
        }

        // POST: tbl_Book/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BOOK_ID,BOOK_NAME,BOOK_AUTHOR,BOOK_PICTURE,BOOK_DETAIL,BOOK_PDF,CATEGORY_FID")] tbl_Book tbl_Book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CATEGORY_FID = new SelectList(db.tbl_BookCategory, "CATEGORY_ID", "CATEGORY_NAME", tbl_Book.CATEGORY_FID);
            return View(tbl_Book);
        }

        // GET: tbl_Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Book tbl_Book = db.tbl_Book.Find(id);
            if (tbl_Book == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Book);
        }

        // POST: tbl_Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Book tbl_Book = db.tbl_Book.Find(id);
            db.tbl_Book.Remove(tbl_Book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DarulAman/Views/tbl_Book/Create.cshtml
@model DarulAman.Models.tbl_Book

@{
    ViewBag.Title = "Create";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Create</h2>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading-center" align="center">Book</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_AUTHOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_AUTHOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_AUTHOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_PICTURE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_PICTURE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_PICTURE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_DETAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_DETAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_DETAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_PDF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_PDF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_PDF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_FID, "CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Create</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_Book/Delete.cshtml
@model DarulAman.Models.tbl_Book

@{
    ViewBag.Title = "Delete";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Delete</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<p class="heading" align="center">Are you sure you want to delete this?</p>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            tbl_BookCategory.CATEGORY_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_BookCategory.CATEGORY_NAME)
        </dd>

        <dt>
            BOOK_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_NAME)
        </dd>

        <dt>
            BOOK_AUTHOR
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_AUTHOR)
        </dd>

        <dt>
            BOOK_PICTURE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_PICTURE)
        </dd>

        <dt>
            BOOK_DETAIL
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_DETAIL)
        </dd>

        <dt>
            BOOK_PDF
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_PDF)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
            <button class="custombtn">Delete</button>
        </div>
    }
</div>

DarulAman/Views/tbl_Book/Details.cshtml
@model DarulAman.Models.tbl_Book

@{
    ViewBag.Title = "Details";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Detail</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <p class="heading-center" align="center">Book</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            tbl_BookCategory.CATEGORY_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_BookCategory.CATEGORY_NAME)
        </dd>

        <dt>
            BOOK_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_NAME)
        </dd>

        <dt>
            BOOK_AUTHOR
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_AUTHOR)
        </dd>

        <dt>
            BOOK_PICTURE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_PICTURE)
        </dd>

        <dt>
            BOOK_DETAIL
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_DETAIL)
        </dd>

        <dt>
            BOOK_PDF
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BOOK_PDF)
        </dd>

    </dl>
</div>
<div align="center">
    <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
    <a href="@Url.Action("Edit", "tbl_Book", new { id = Model.BOOK_ID})" class="custombtn">Edit</a>
</div>

DarulAman/Views/tbl_Book/Edit.cshtml
@model DarulAman.Models.tbl_Book

@{
    ViewBag.Title = "Edit";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Edit</h2>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading-center" align="center">Book</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BOOK_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_AUTHOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_AUTHOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_AUTHOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_PICTURE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_PICTURE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_PICTURE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_DETAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_DETAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_DETAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BOOK_PDF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BOOK_PDF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BOOK_PDF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORY_FID, "CATEGORY_FID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CATEGORY_FID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CATEGORY_FID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Save</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_Book/Index.cshtml
@model IEnumerable<DarulAman.Models.tbl_Book>

@{
    ViewBag.Title = "Index";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Index</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">
            <p class="heading">Book</p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">

            <a style="float:right;" class="btn btn-outline-info btn-lg" href="@Url.Action("Create", "tbl_Book")"><b>Create New</b> </a>
        </div>

    </div>
</div>
<br />
<table class="table">
    <tr>
        <th>
         CATEGORY_NAME
        </th>
        <th>
            BOOK_NAME
        </th>
        <th>
            BOOK_AUTHOR
        </th>
        <th>
            BOOK_PICTURE
        </th>
     
        <th>
            BOOK_PDF
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tbl_BookCategory.CATEGORY_NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BOOK_NAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BOOK_AUTHOR)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BOOK_PICTURE)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.BOOK_PDF)
            </td>
            <td>
                <a href="@Url.Action("Edit", "tbl_Book", new { id=item.BOOK_ID})">
                    <i class="fa fa-edit btn btn-success  "></i>
                </a>|
                <a href="@Url.Action("Details", "tbl_Book", new { id=item.BOOK_ID})">
                    <i class="fa fa-book btn btn-warning"></i>
                </a>|
                <a href="@Url.Action("Delete", "tbl_Book", new { id=item.BOOK_ID })">
                    <i class="fa fa-trash btn btn-danger"></i>
                </a>
            </td>
        </tr>
    }

</table>