DarulAman/Models/tbl_TeachingCourse.cs
namespace DarulAman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tbl_TeachingCourse
    {
        [Key]
        public int COURSE_ID { get; set; }

        [Required]
        [StringLength(50)]
        public string COURSE_NAME { get; set; }
    }
}

DarulAman/Controllers/tbl_TeachingCourseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DarulAman.Models;

namespace DarulAman.Controllers
{
    public class tbl_TeachingCourseController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_TeachingCourse
        public ActionResult Index()
        {
            return View(db.tbl_TeachingCourse.ToList());
        }

        // GET: tbl_TeachingCourse/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_TeachingCourse tbl_TeachingCourse = db.tbl_TeachingCourse.Find(id);
            if (tbl_TeachingCourse == null)
            {
                return HttpNotFound();
            }
            return View(tbl_TeachingCourse);
        }

        // GET: tbl_TeachingCourse/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tbl_TeachingCourse/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "COURSE_ID,COURSE_NAME")] tbl_TeachingCourse tbl_TeachingCourse)
        {
            if (ModelState.IsValid)
            {
                db.tbl_TeachingCourse.Add(tbl_TeachingCourse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_TeachingCourse);
        }

        // GET: tbl_TeachingCourse/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_TeachingCourse tbl_TeachingCourse = db.tbl_TeachingCourse.Find(id);
            if (tbl_TeachingCourse == null)
            {
                return HttpNotFound();
            }
            return View(tbl_TeachingCourse);
        }

        // POST: tbl_TeachingCourse/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "COURSE_ID,COURSE_NAME")] tbl_TeachingCourse tbl_TeachingCourse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_TeachingCourse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_TeachingCourse);
        }

        // GET: tbl_TeachingCourse/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_TeachingCourse tbl_TeachingCourse = db.tbl_TeachingCourse.Find(id);
            if (tbl_TeachingCourse == null)
            {
                return HttpNotFound();
            }
            return View(tbl_TeachingCourse);
        }

        // POST: tbl_TeachingCourse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_TeachingCourse tbl_TeachingCourse = db.tbl_TeachingCourse.Find(id);
            db.tbl_TeachingCourse.Remove(tbl_TeachingCourse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DarulAman/Views/tbl_TeachingCourse/Create.cshtml
@model DarulAman.Models.tbl_TeachingCourse

@{
    ViewBag.Title = "Create";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Create</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading" align="center">Teaching Course</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.COURSE_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COURSE_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COURSE_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Create</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_TeachingCourse/Delete.cshtml
@model DarulAman.Models.tbl_TeachingCourse

@{
    ViewBag.Title = "Delete";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Delete</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<p class="heading" align="center">Are you sure you want to delete this?</p>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            COURSE_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COURSE_NAME)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
            <button class="custombtn">Delete</button>
        </div>
    }
</div>

DarulAman/Views/tbl_TeachingCourse/Details.cshtml
@model DarulAman.Models.tbl_TeachingCourse

@{
    ViewBag.Title = "Details";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Detail</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <p class="heading" align="center">Teaching Course</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            COURSE_NAME
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COURSE_NAME)
        </dd>

    </dl>
</div>
<div align="center">
    <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
    <a href="@Url.Action("Edit", "tbl_TeachingCourse", new { id = Model.COURSE_ID})" class="custombtn">Edit</a>
</div>

DarulAman/Views/tbl_TeachingCourse/Edit.cshtml
@model DarulAman.Models.tbl_TeachingCourse

@{
    ViewBag.Title = "Edit";
}
<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Edit</h2>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading" align="center">Teaching Course</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.COURSE_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.COURSE_NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.COURSE_NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.COURSE_NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Save</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_TeachingCourse/Index.cshtml
@model IEnumerable<DarulAman.Models.tbl_TeachingCourse>

@{
    ViewBag.Title = "Index";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Index</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">
            <p class="heading">Teaching Course</p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">

            <a style="float:right;" class="btn btn-outline-info btn-lg" href="@Url.Action("Create", "tbl_TeachingCourse")"><b>Create New</b> </a>
        </div>

    </div>
</div>
<br />

<table class="table">
    <tr>
        <th>
            COURSE_NAME
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.COURSE_NAME)
    </td>
    <td>
        <a href="@Url.Action("Edit", "tbl_TeachingCourse", new { id=item.COURSE_ID})">
            <i class="fa fa-edit btn btn-success  "></i>
        </a>|
        <!--
            <a href="@Url.Action("Details", "tbl_TeachingCourse", new { id=item.COURSE_ID })">
                <i class="fa fa-book btn btn-warning"></i>
            </a>|-->
            <a href="@Url.Action("Delete", "tbl_TeachingCourse", new { id=item.COURSE_ID })">
                <i class="fa fa-trash btn btn-danger"></i>
            </a>

        </td>

    </tr>
        }

    </table>