DarulAman/Models/tbl_FAQs.cs
namespace DarulAman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class tbl_FAQs
    {
        [Key]
        public int FAQ_ID { get; set; }

        [Required]
        [StringLength(500)]
        public string FAQ_QUESTION { get; set; }

        [Required]
        [StringLength(500)]
        public string FAQ_ANSWER { get; set; }
    }
}

DarulAman/Controllers/tbl_FAQsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DarulAman.Models;

namespace DarulAman.Controllers
{
    public class tbl_FAQsController : Controller
    {
        private Model1 db = new Model1();

        // GET: tbl_FAQs
        public ActionResult Index()
        {
            return View(db.tbl_FAQs.ToList());
        }

        // GET: tbl_FAQs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_FAQs tbl_FAQs = db.tbl_FAQs.Find(id);
            if (tbl_FAQs == null)
            {
                return HttpNotFound();
            }
            return View(tbl_FAQs);
        }

        // GET: tbl_FAQs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tbl_FAQs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FAQ_ID,FAQ_QUESTION,FAQ_ANSWER")] tbl_FAQs tbl_FAQs)
        {
            if (ModelState.IsValid)
            {
                db.tbl_FAQs.Add(tbl_FAQs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_FAQs);
        }

        // GET: tbl_FAQs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_FAQs tbl_FAQs = db.tbl_FAQs.Find(id);
            if (tbl_FAQs == null)
            {
                return HttpNotFound();
            }
            return View(tbl_FAQs);
        }

        // POST: tbl_FAQs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FAQ_ID,FAQ_QUESTION,FAQ_ANSWER")] tbl_FAQs tbl_FAQs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_FAQs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_FAQs);
        }

        // GET: tbl_FAQs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_FAQs tbl_FAQs = db.tbl_FAQs.Find(id);
            if (tbl_FAQs == null)
            {
                return HttpNotFound();
            }
            return View(tbl_FAQs);
        }

        // POST: tbl_FAQs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_FAQs tbl_FAQs = db.tbl_FAQs.Find(id);
            db.tbl_FAQs.Remove(tbl_FAQs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DarulAman/Views/tbl_FAQs/Create.cshtml
@model DarulAman.Models.tbl_FAQs

@{
    ViewBag.Title = "Create";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Create</h2>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading-center" align="center">FAQs</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FAQ_QUESTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAQ_QUESTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAQ_QUESTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FAQ_ANSWER, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAQ_ANSWER, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAQ_ANSWER, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Create</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_FAQs/Delete.cshtml
@model DarulAman.Models.tbl_FAQs

@{
    ViewBag.Title = "Delete";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Delete</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<p class="heading" align="center">Are you sure you want to delete this?</p>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            FAQ_QUESTION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAQ_QUESTION)
        </dd>

        <dt>
            FAQ_ANSWER
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAQ_ANSWER)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
            <button class="custombtn">Delete</button>
        </div>
    }
</div>

DarulAman/Views/tbl_FAQs/Details.cshtml
@model DarulAman.Models.tbl_FAQs

@{
    ViewBag.Title = "Details";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Detail</h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <p class="heading-center" align="center">FAQs</p>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            FAQ_QUESTION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAQ_QUESTION)
        </dd>

        <dt>
            FAQ_ANSWER
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FAQ_ANSWER)
        </dd>

    </dl>
</div>
<div align="center">
    <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
    <a href="@Url.Action("Edit", "tbl_FAQs", new { id = Model.FAQ_ID})" class="custombtn">Edit</a>
</div>

DarulAman/Views/tbl_FAQs/Edit.cshtml
@model DarulAman.Models.tbl_FAQs

@{
    ViewBag.Title = "Edit";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Edit</h2>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p class="heading-center" align="center">FAQs</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FAQ_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FAQ_QUESTION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAQ_QUESTION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAQ_QUESTION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FAQ_ANSWER, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FAQ_ANSWER, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FAQ_ANSWER, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="indexback">@Html.ActionLink("Back to List", "Index") </button> |
                <button class="custombtn">Save</button>
            </div>
        </div>
    </div>
}

DarulAman/Views/tbl_FAQs/Index.cshtml
@model IEnumerable<DarulAman.Models.tbl_FAQs>

@{
    ViewBag.Title = "Index";
}

<div class="midde_cont">
    <div class="container-fluid">
        <div class="row column_title">
            <div class="col-md-12">
                <div class="page_title">
                    <h2>Index</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">
            <p class="heading">FAQs</p>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">

            <a style="float:right;" class="btn btn-outline-info btn-lg" href="@Url.Action("Create", "tbl_FAQs")"><b>Create New</b> </a>
        </div>

    </div>
</div>
<br />


<div class="midde_cont">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="white_shd full margin_bottom_30">
                    <div class="full graph_head">
                        <div class="heading1 margin_0">
                           
                        </div>
                    </div>
                    <div class="table_section padding_infor_info">
                        <div class="table-responsive-sm">
                            <table class="table table-active table-bordered">
                                <tr>
                                    <th>
                                        FAQ_QUESTION
                                    </th>
                                    <th width="500px">
                                        FAQ_ANSWER
                                    </th>

                                    <th></th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FAQ_QUESTION)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.FAQ_ANSWER)
                                        </td>

                                        <td>
                                            <a href="@Url.Action("Edit", "tbl_FAQs", new { id=item.FAQ_ID})">
                                                <i class="fa fa-edit btn btn-success  "></i>
                                            </a>|
                                            <!---
    <a href="@Url.Action("Details", "tbl_FAQs", new { id=item.FAQ_ID})">
        <i class="fa fa-book btn btn-warning"></i>
    </a>|-->
                                            <a href="@Url.Action("Delete", "tbl_FAQs", new { id=item.FAQ_ID })">
                                                <i class="fa fa-trash btn btn-danger"></i>
                                            </a>

                                        </td>

                                    </tr>
                                }

                            </table>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>